#ifndef Const_H
#define Const_H

/*
DEFINITION DES CONSTANTES IO COOPR
COOPR
*/

#define COULEUR_JAUNE 0
#define COULEUR_VERT 1


#define CHAINE_SECONDAIRE_STOP 1500
#define CHAINE_SECONDAIRE_MARCHE 1700

#define CHAINE_SECONDAIRE_POSITION_RANGEE 997
#define CHAINE_SECONDAIRE_POSITION_SOL 1847
#define CHAINE_SECONDAIRE_POSITION_MI 1600

#define SEUIL_BUMPER 600
#define SEUIL_IR_HAUT 600
#define SEUIL_IR_BAS 600


#define PAS_INCREMENTATION 3
#define HAUT 0
#define MILIEU 1
#define BAS 2

//turbine
#define TURBINE_OFF 1000
#define TURBINE_ON 1350

// nozzle
#define NOZZLE_HAUT 1636
#define NOZZLE_MIDDLE 1475
#define NOZZLE_BAS 1275


#define CHENILLE_LATERALE_ARRET 1500
#define CHENILLE_LATERALE_DEPLACEMENT_GAUCHE 1000
#define CHENILLE_LATERALE_DEPLACEMENT_DROITE 2000



//pince

#define GARDE_GAUCHE_ON 2049
#define GARDE_GAUCHE_OFF 1763
#define GARDE_DROITE_ON 1690
#define GARDE_DROITE_OFF 2026

#define BRAS_DROITE_RANGE 1031
#define BRAS_DROITE_MIDDLE 1500
#define BRAS_DROITE_BAS 1797

#define BRAS_GAUCHE_RANGE 1919
#define BRAS_GAUCHE_MIDDLE 1500
#define BRAS_GAUCHE_BAS 1144






#endif
